---

- ansible.builtin.include: disable_xinetd.yml
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - disable_xinetd

- ansible.builtin.include: server_sshd_user.yml
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - server_auth

- ansible.builtin.include: server_ssh_keys.yml
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - server_ssh_keys

# run if server_also_client set, default is True
- ansible.builtin.include: client_security.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when: server_also_client|bool
  tags:
    - client_security

...
