---

- ansible.builtin.include: debian_server.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - ansible_os_family == "Debian"
    - (ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 10) or (ansible_distribution == "Ubuntu")
  tags:
    - debian_server

- ansible.builtin.include: rhel7_centos7_server.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int == 7
  tags:
    - rhel7_centos7_server

- ansible.builtin.include: rhel8_centos8_server.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int == 8
  tags:
    - rhel8_centos8_server

- ansible.builtin.include: disable_xinetd.yml
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - disable_xinetd

- ansible.builtin.include: server_sshd_user.yml
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - server_auth

- ansible.builtin.include: server_ssh_keys.yml
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - server_ssh_keys

# run if server_also_client set, default is True
- ansible.builtin.include: client_security.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when: server_also_client|bool
  tags:
    - client_security

...
