---

# D Simpson 2021,2023 ds-04

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

- block:

  - name: amanda server dependencies
    ansible.builtin.dnf:
     name:
      # needed for lto tapes
      - mt-st
      - mtx
      # needed for default amanda server email /bin/Mail -> /bin/mailx
      - mailx
      - glib*
      #- xinetd kept for reference
      - perl-Data-Dumper
      - perl-Encode-Locale
      - perl-JSON
      #- perl-URI-Escape use CPAN
      - perl-XML-Simple
      - perl
      - perl-CPAN
      - lsscsi
      - tar #just to be sure
     state: installed

  - name: (RHEL/Centos 8x) install amanda-server from repos
    ansible.builtin.dnf:
     name: amanda-server
     update_cache: yes
    when:
     - ansible_os_family == "RedHat"
     - ansible_distribution_major_version|int >= 8

  become: "True"
...
