---

# D Simpson 2021,2023 ds-04

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.



# VAGRANT---------------------------------------------------------------------------------
# (1) - setup hostname and /etc/hosts for vagrant (if vagrant)
- ansible.builtin.import_playbook: playbook_amanda_server_vagrant_hostname.yml

# INSTALL PACKAGES FOR CLIENT AND SERVER--------------------------------------------------
# (2) - install server packages including dependencies
- ansible.builtin.import_playbook: playbook_amanda_server_pkg.yml
# (3) - install client package
- ansible.builtin.import_playbook: playbook_amanda_client_pkg.yml

# MAIN CONFIG-----------------------------------------------------------------------------
# (4) - main server config (ssh etc)
- ansible.builtin.import_playbook: playbook_amanda_server.yml
# (5) - main client config (ssh etc)
- ansible.builtin.import_playbook: playbook_amanda_client.yml

# ZMANDA FIXES----------------------------------------------------------------------------
# (6) - zmanda package install specific fixes (if applicable)
- ansible.builtin.import_playbook: playbook_zmanda_fixes.yml

# SSH KEYS--------------------------------------------------------------------------------
# (7) - copy keys for ssh
- ansible.builtin.import_playbook: playbook_amanda_copy_keys.yml

# CLIENT RESTORE--------------------------------------------------------------------------
# (8) configure clients for restore
- ansible.builtin.import_playbook: playbook_amanda_client_restore.yml

# DUMP/BACKUP CONFIGURATION---------------------------------------------------------------
# (9) - write backup configuration on server, NOTE to deploy test vtape config use: -e deploy_test_vtape_cfg=True
- ansible.builtin.import_playbook: playbook_amanda_server_cfg.yml

# SUMMARY/HINTS---------------------------------------------------------------------------
# (10) - summary and hints
- ansible.builtin.import_playbook: playbook_amanda_deploy_helper.yml
...
