---

# repo package install
- ansible.builtin.include: repo_package_client.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
   - install_amanda|bool
   - not use_zmanda_package|bool
   - (ansible_os_family == "Debian" or ansible_os_family == "RedHat" or ansible_os_family == "Suse")
  tags:
   - repo_client

# zmanda package install
- ansible.builtin.include: zmanda_package_client.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
   - install_amanda|bool
   - use_zmanda_package|bool
   - '"amanda_server" not in group_names' # package conflict between server/client in rhel7
   - ansible_distribution != 'Fedora'
   - (ansible_os_family == "Debian" or ansible_os_family == "RedHat" or ansible_os_family == "Suse")
  tags:
   - zmanada_client

...
