---

# D Simpson 2021,2023 ds-04

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

- block:

 # SET FACTS ********************************************************************************************

   - name: Initiliase empty dict to hold client package key/value
     ansible.builtin.set_fact:
       local_client_name: {}

   # OS FAMILY BASED - client name
   - name: "SET FACT DEPENDENCIES {{ ansible_os_family }} - client name"
     ansible.builtin.set_fact:
      local_client_name: "{{ item.value }}"
     loop: "{{ lookup('dict', amanda_packages ) }}"
     when:
      - ansible_os_family+'_client_name' in item.key
      - ansible_os_family in family_only_detection

   # OS FAMILY + VERSION BASED - client name
   - name: SET FACT DEPENDENCIES - client name
     ansible.builtin.set_fact:
      local_client_name: "{{ item.value }}"
     loop: "{{ lookup('dict', amanda_packages ) }}"
     when:
      - ansible_os_family+'_'+ansible_distribution_major_version+'_client_name' in item.key
      - ansible_os_family in family_and_version_detection
      - ansible_distribution not in distro_and_version_detection

   # DISTRO + VERSION BASED - client name
   - name: SET FACT DEPENDENCIES - client name
     ansible.builtin.set_fact:
      local_client_name: "{{ item.value }}"
     loop: "{{ lookup('dict', amanda_packages ) }}"
     when:
      - ansible_distribution+'_'+ansible_distribution_major_version+'_client_name' in item.key
      - ansible_distribution in distro_and_version_detection

 # END SET FACTS *****************************************************************************************

   - name: APT - Debian/Ubuntu - Client repo install
     ansible.builtin.apt:
      name: "{{ item.key }}"
      state: "{{ item.value }}"
      update_cache: true
     loop: "{{ lookup('dict', local_client_name, wantlist=true) }}"
     when: ansible_pkg_mgr == 'apt'

   - name: DNF - RHEL-like => 8 - Client repo install
     ansible.builtin.dnf:
      name: "{{ item.key }}"
      state: "{{ item.value }}"
      update_cache: true
     loop: "{{ lookup('dict', local_client_name, wantlist=true) }}"
     when: 
      - ansible_pkg_mgr == 'dnf'
      - ansible_distribution_major_version|int >= 8

   - name: YUM - RHEL-like 7 - Client repo install
     ansible.builtin.yum:
      name: "{{ item.key }}"
      state: "{{ item.value }}"
      update_cache: true
     loop: "{{ lookup('dict', local_client_name, wantlist=true) }}"
     when:
      - ansible_pkg_mgr == 'yum'
      - ansible_distribution_major_version|int == 7

   - name: ZYPPER - Suse family - Client repo install
     ansible.builtin.zypper:
      name: "{{ item.key }}"
      state: "{{ item.value }}"
      update_cache: true
     loop: "{{ lookup('dict', local_client_name, wantlist=true) }}"
     when: ansible_pkg_mgr == 'zypper'

  become: true
...
