---
  # debian and ubuntu
- ansible.builtin.include: repo_debian_server.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - install_amanda|bool
    - not use_zmanda_package|bool
    - ansible_os_family == 'Debian'
    - (ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 10) or (ansible_distribution == "Ubuntu")
  tags:
    - debian_server

  # rhel7x family not fedora
- ansible.builtin.include: repo_rhel7_centos7_server.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - install_amanda|bool
    - not use_zmanda_package|bool
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'
    - ansible_distribution_major_version|int == 7
  tags:
    - rhel7_centos7_server

  # rhel8x family not fedora
- ansible.builtin.include: repo_rhel8_centos8_server.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - install_amanda|bool
    - not use_zmanda_package|bool
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'
    - ansible_distribution_major_version|int >= 8
  tags:
    - rhel8_centos8_server

  # fedora
- ansible.builtin.include: repo_fedora_server.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - install_amanda|bool
    - not use_zmanda_package|bool
    - ansible_distribution == 'Fedora'
    - ansible_distribution_major_version|int >= 35
  tags:
    - fedora_server


 # ---ZMANDA---

# zmanda package install
- ansible.builtin.include: zmanda_package_server.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
   - install_amanda|bool
   - use_zmanda_package|bool
   - ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

...
