---

# ---AMANDA (REPO)---

- ansible.builtin.include: repo_package_server.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - install_amanda|bool
    - not use_zmanda_package|bool
    - supported_family_version_combination or supported_distro_version_combination


# ---ZMANDA (DIRECT DOWNLOAD URL)---

- ansible.builtin.include: zmanda_package_server.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - install_amanda|bool
    - use_zmanda_package|bool
    - ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

...
