---

# repo package install
- ansible.builtin.include: repo_package_client.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
   - install_amanda|bool
   - not use_zmanda_package|bool
   - (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7) or (ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 10) or (ansible_distribution == "Ubuntu")
  tags:
   - repo_client

# zmanda package install
- ansible.builtin.include: zmanda_package_client.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
   - install_amanda|bool
   - use_zmanda_package|bool
   - '"amanda_server" not in group_names' #package conflict between server/client in rhel7
   - (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7) or (ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 10) or (ansible_distribution == "Ubuntu")
  tags:
   - zmanada_client

- ansible.builtin.include: amrecover_fix.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
   - install_amanda|bool
   #- not use_zmanda_package|bool
   - (ansible_os_family == "RedHat" and ansible_distribution_major_version|int > 7) or (ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 10) or (ansible_distribution == "Ubuntu")
   - "'amanda_client_restore' in group_names"
  tags:
   - amrecover_fix

- ansible.builtin.include: disable_xinetd.yml
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
   - disable_xinetd

# ssh and local user security
- ansible.builtin.include: client_sshd_user.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
   - (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7) or (ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 10) or (ansible_distribution == "Ubuntu")
  tags:
   - client_sshd

# setup amanda-security.conf
- ansible.builtin.include: client_security.yml
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
   - client_security

...
