---

# package install
- include: client.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
   - (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7) or (ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 10)
  tags:
   - client

- include: disable_xinetd.yml
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
   - disable_xinetd

# ssh and local user security
- include: client_sshd_user.yml
  ignore_errors: "{{ ansible_check_mode }}"
  when:
   - (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7) or (ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 10)
  tags:
   - client_sshd

# setup amanda-security.conf
- include: client_security.yml
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
   - client_security

...
