---
# Amanda version is from repo, unless RHEL7 family which is download from zmanda

# should the server be able to backup itself etc.
server_also_client: 'True'
# can the client connect to the server for restore
client_can_restore: 'True'

#-----------SSH--------------
# enable the update of known hosts on the server, using the following vars
update_server_known_hosts: 'True'
update_client_restore_known_hosts: 'True'
known_hosts_key_type: 'ed25519'
ssh_key_algo: 'ed25519' # prefer ed25519 to rsa, also see NOTES bottom

# the name of the server and client_restore keypair
server_ssh_keypair: amdump_id_{{ ssh_key_algo|default('ed25519') }} # default name from RPM is id_rsa_amdump
client_restore_ssh_keypair: amrecover_id_{{ ssh_key_algo|default('ed25519') }} # default name from RPM is id_rsa_amrecover
#--------END-SSH-------------

#----------PACKAGES----------
# RHEL7 family pacakges, main repos are older, here from zmanda:
client_rpm:
 - { url: "https://cdn.zmanda.com/downloads/community/Amanda/3.5.3/RHEL-7/amanda-backup_client-3.5.3.git.18189a34-1.rhel7.x86_64.rpm", checksum: "sha256:67035dcc42a363761a207b94a9fa8c7d72ba7fa17ad097160e5f38c2b83557f6", dest: "/root/" }
server_rpm:
 - { url: "https://cdn.zmanda.com/downloads/community/Amanda/3.5.3/RHEL-7/amanda-backup_server-3.5.3.git.18189a34-1.rhel7.x86_64.rpm", checksum: "sha256:5e151b42e9f8c479541aec5a1fbbf83693433c57326f22653d1ddb965b93b567", dest: "/root/" }

# RHEL8 family packages come from repos
# Debian/Ubuntu packages come from repos
#-----END--PACKAGES---------

#-----OS--VARS--------------

#security prefix - also note NO trailing comma here
#N.B. server ending like command="/usr/lib/amanda/amandad -auth=ssh amdump"
#N.B. client ending like command="/usr/lib/amanda/amandad -auth=ssh amindexd amidxtaped"
std_ssh_key_opts: 'no-port-forwarding,no-X11-forwarding,no-agent-forwarding'

debian_user: 'backup'
debian_group: 'backup'
debian_user_home: '/var/backups'

redhat_user: 'amandabackup'
redhat_group: 'disk'
redhat_user_home: '/var/lib/amanda'

# list of known locations to search for amandad (depending on distro/package etc.)
amandad_search_paths:
  - /usr/lib64/amanda/amandad
  - /usr/libexec/amanda/amandad
  - /usr/lib/amanda/amandad
  - /usr/local/libexec/amanda/amandad
  - /usr/local/libexec/amandad

# compensate for packaging issue if ambind not found, by installing server package
ambind_server_provide: 'True'
ambind_fix_alias1: >
 alias amdump='echo "amdump, refusing invocation - This is a client, but we had to install the server package to fix amrecover (this message is a .bash_profile alias)"'
ambind_fix_alias2: >
 alias amcheck='echo "amcheck, refusing invocation - This is a client, but we had to install the server package to fix amrecover (this message is a .bash_profile alias)"'
ambind_bash_profile_dict: { 'alias amdump': "{{ ambind_fix_alias1 }}", 'alias amcheck': "{{ ambind_fix_alias2 }}" }

# list of known locations to search for ambind (depending on distro/package etc.)
ambind_search_paths:
  - /usr/lib64/amanda/ambind
  - /usr/lib/amanda/ambind

#-END-OS--VARS-------------

#-----VAGRANT--VARS--------------
#vagrant_net_regex: '192.168.[0-9]*.[0-9]*'
#-END-VAGRANT--VARS-------------

#--------------------------------------------------------------------------------
# NOTES
# standard rsa keys will be removed if rsa is not chosen as ssh_key_algo
# on a RHEL Centos host these come from the RPM:
# id_rsa_amdump,id_rsa_amdump.pub,id_rsa_amrecover,id_rsa_amrecover.pub

...
