---
# NOTES
# 1) Version - default Amanda version is from repo, unless zmanda chosen (see var)
# 
# 2) SSH - standard rsa keys will be removed if rsa is not chosen as ssh_key_algo
# on a RHEL Centos host these come from the RPM:
# id_rsa_amdump,id_rsa_amdump.pub,id_rsa_amrecover,id_rsa_amrecover.pub

#----------OS SUPPORT--------------------------

supported_family_version_combination: >
  (ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 7)
  or (ansible_os_family == 'Debian' and ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 10)
  or (ansible_os_family == 'Suse')
supported_distro_version_combination: >
  ((ansible_distribution == 'Fedora' and ansible_distribution_major_version|int >= 35)
  or (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 22))

# FOR REFERENCE - These vars are not called, but the values are used in the server packages role
uses_apt_package_manager: >
 (ansible_os_family == 'Debian' and ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 10)
  or (ansible_os_family == 'Debian' and ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 22)
uses_dnf_package_manager: >
  (ansible_distribution != 'Fedora' and 'ansible_os_family == ''RedHat'' and ansible_distribution_major_version|int >= 8')
  or (ansible_distribution == 'Fedora' and ansible_distribution_major_version|int >= 35 ))
uses_yum_package_manager: >
  'ansible_os_family == ''RedHat'' and ansible_distribution_major_version|int == 7'
uses_zypper_package_manager: >
  'ansible_os_family == ''Suse'''

#----------OS SUPPORT---------------------------

#----------INSTALL TYPE---------------------------

#global toggle, disable to stop installation and just configure
install_amanda: true
#choose zmanda install via download url OR not (use default repos and amanda package)
use_zmanda_package: true

#----------END INSTALL TYPE-----------------------

#-----------SELF, BACKUP AND RESTORE--------------
# should the server be able to backup itself etc.
server_also_client: true
# can the client connect to the server for restore
client_can_restore: true

# remove DailySet1 dir from clients (comes from package)
# /etc/amanda/DailySet1 -> use /etc/amanda/amanda-client.conf
always_remove_client_DailySet1: true
#-----------END-SELF BACKUP AND RESTORE-----------

#-----------SSH-----------------------------------
# enable the update of known hosts on the server, using the following vars
update_server_known_hosts: true
update_client_restore_known_hosts: true
known_hosts_key_type: 'ed25519'
ssh_key_algo: 'ed25519' # prefer ed25519 to rsa, also see NOTES bottom

# the name of the server and client_restore keypair
server_ssh_keypair: amdump_id_{{ ssh_key_algo | default('ed25519') }} # default name from RPM is id_rsa_amdump
client_restore_ssh_keypair: amrecover_id_{{ ssh_key_algo | default('ed25519') }} # default name from RPM is id_rsa_amrecover
#--------END-SSH----------------------------------

#----------PACKAGES-------------------------------

# 3.5.3 dictionary, debian11 requires fixes which roles perform

#amandad: must be executed as the "amandabackup" user instead of the "backup" user
#amandad: critical (fatal): create debug directory "/var/log/amanda/amandad/": Permission denied

# Amanda packages direct from OS repos - apt/dnf/yum/zypper installation

family_only_detection: ['Suse']
family_and_version_detection: ['RedHat']
distro_and_version_detection: ['Debian','Fedora','Ubuntu']

#apt_pkg_mgr:
# - Debian
#dnf_pkg_mgr:
# - Fedora
# - RedHat
#yum_pkg_mgr:
# - RedHat
#zypper_pkg_mgr:
# - Suse





amanda_packages:
  # usage is distro + major ver
  Debian_11_client_name:    { 'amanda-client': 'latest' }
  Debian_11_server_name:    { 'amanda-server': 'latest' }
  Debian_11_server_depends: {}
  Debian_11_extras:         { 'acl':                'present',
                              'tar':                'present' }
  Debian_11_lto:            { 'lsscsi':             'present',
                              'mtx':                'present', 
                              'mt-st':              'present' }
  # usage is distro + major ver
  Fedora_37_client_name:      { 'amanda-client': 'latest' }
  Fedora_37_server_name:      { 'amanda-server': 'latest' }
  Fedora_37_server_depends:   { 'perl':               'present',
                                'perl-Data-Dumper':   'present',
                                'perl-Encode-Locale': 'present',
                                'perl-JSON':          'present',
                                'perl-XML-Simple':    'present' }
  Fedora_37_extras:           { 'acl':                'present',
                                'tar':                'present' }
  Fedora_37_lto:              { 'lsscsi':             'present',
                                'mtx':                'present' }
  # usage is family + major ver
  RedHat_7_client_name:    { 'amanda-client': 'latest' }
  RedHat_7_server_name:    { 'amanda-server': 'latest' }
  RedHat_7_server_depends: { 'perl':               'present',
                             'perl-CPAN':          'present',
                             'perl-Data-Dumper':   'present',
                             'perl-Encode-Locale': 'present',
                             'perl-JSON':          'present',
                             'perl-XML-Simple':    'present' }
  RedHat_7_extras:         { 'acl':                'present',
                             'tar':                'present' }
  RedHat_7_lto:            { 'lsscsi':             'present',
                             'mtx':                'present', 
                             'mt-st':              'present' }
  # usage is family + major ver
  RedHat_8_client_name:    { 'amanda-client': 'latest' }
  RedHat_8_server_name:    { 'amanda-server': 'latest' }
  RedHat_8_server_depends: { 'perl':               'present',
                             'perl-Data-Dumper':   'present',
                             'perl-Encode-Locale': 'present',
                             'perl-JSON':          'present',
                             'perl-XML-Simple':    'present' }
  RedHat_8_extras:         { 'acl':                'present',
                             'tar':                'present' }
  RedHat_8_lto:            { 'lsscsi':             'present',
                             'mtx':                'present', 
                             'mt-st':              'present' }
  # usage is family
  Suse_client_name:        { 'amanda':             'latest' }
  Suse_server_name:        { 'amanda':             'latest' }
  Suse_server_depends:     { 'perl':               'present',
                             'perl-Encode-Locale': 'present',
                             'perl-JSON':          'present' }
  Suse_extras:             { 'acl':                'present',
                             'tar':                'present' }
  Suse_lto:                { 'lsscsi':             'present',
                             'mtx':                'present' }
  # usage is distro + major ver
  Ubuntu_22_client_name:    { 'amanda-client': 'latest' }
  Ubuntu_22_server_name:    { 'amanda-server': 'latest' }
  Ubuntu_22_server_depends: {}
  Ubuntu_22_extras:         { 'acl':                'present',
                                 'tar':                'present' }
  Ubuntu_22_lto:            { 'lsscsi':             'present',
                                 'mtx':                'present', 
                                 'mt-st':              'present' }

# Alternative option, packages direct from Zmanda
zmanda_packages:
  RedHat_7: # is also centos7
    client:
      url: "https://cdn.zmanda.com/downloads/community/Amanda/3.5.3/RHEL-7/amanda-backup_client-3.5.3.git.18189a34-1.rhel7.x86_64.rpm"
      checksum: "sha256:67035dcc42a363761a207b94a9fa8c7d72ba7fa17ad097160e5f38c2b83557f6"
      dest: "/root/"
      depends: []
      dir_perms: []
    server:
      url: "https://cdn.zmanda.com/downloads/community/Amanda/3.5.3/RHEL-7/amanda-backup_server-3.5.3.git.18189a34-1.rhel7.x86_64.rpm"
      checksum: "sha256:5e151b42e9f8c479541aec5a1fbbf83693433c57326f22653d1ddb965b93b567"
      dest: "/root/"
      depends: []
      dir_perms: []
  Debian_11:
    client:
      url: "https://cdn.zmanda.com/downloads/community/Amanda/3.5.3/Debian-11/amanda-backup-client_3.5.3.git.18189a34-1Debian11_amd64.deb"
      checksum: "sha256:f93ea340ddc13eebae02dc22218b987ff1e3c3a4c94d7f508438c584dbfbd205"
      dest: "/root/"
      depends: ["libxml-simple-perl"]
      dir_perms: []
    server:
      url: "https://cdn.zmanda.com/downloads/community/Amanda/3.5.3/Debian-11/amanda-backup-server_3.5.3.git.18189a34-1Debian11_amd64.deb"
      checksum: "sha256:1e2394ffafdc23254174f25288adb5fc926c514849ca4c0ceeb77790384d9c0a"
      dest: "/root/"
      depends: ["libencode-locale-perl","libjson-perl","libxml-simple-perl","xinetd"]
      dir_perms: ["/var/log/amanda","/var/log/amanda/client","/var/log/amanda/server","/tmp/amanda"] # inclusion of /tmp/amanda as pkg is broken
  Ubuntu_22.04:
    client:
      url: "https://cdn.zmanda.com/downloads/community/Amanda/3.5.3/Ubuntu-22.04/amanda-backup-client_3.5.3.git.d77fa906-1Ubuntu2204_amd64.deb"
      checksum: "sha256:e1ab7ea0babb04cd780cad9dc8dc902e7cfda8802c0532c9751d2c29e7a87294"
      dest: "/root/"
      depends: ["libxml-simple-perl"]
      dir_perms: []
    server:
      url: "https://cdn.zmanda.com/downloads/community/Amanda/3.5.3/Ubuntu-22.04/amanda-backup-server_3.5.3.git.d77fa906-1Ubuntu2204_amd64.deb"
      checksum: "sha256:4136cb05775cf6a119d39a128879869343f2ba51336ac6c38411e31fb212cebd"
      dest: "/root/"
      depends: ["libencode-locale-perl","libjson-perl","libxml-simple-perl"]
      dir_perms: ["/var/log/amanda","/var/log/amanda/client","/var/log/amanda/server","/tmp/amanda"] # inclusion of /tmp/amanda as pkg is broken

# These versions will not be defined here, but you could define the dictionaries in vars dir
# 3.5.2_zmanda_packages
# 3.5_zmanda_packages

#-----END--PACKAGES-------------------------------

#-----OS--VARS------------------------------------

#security prefix - also note NO trailing comma here
#N.B. server ending like command="/usr/lib/amanda/amandad -auth=ssh amdump"
#N.B. client ending like command="/usr/lib/amanda/amandad -auth=ssh amindexd amidxtaped"
std_ssh_key_opts: 'no-port-forwarding,no-X11-forwarding,no-agent-forwarding'

# 
debian_user: 'backup'
debian_group: 'backup'
debian_user_home: '/var/backups'
#  ------- AND is also zmanda name
redhat_user: 'amandabackup'
redhat_group: 'disk'
redhat_user_home: '/var/lib/amanda'
# 
suse_user: 'amanda'
suse_group: 'amanda'
suse_user_home: '/var/lib/amanda'

# list of known locations to search for amandad (depending on distro/package etc.)
amandad_search_paths:
  - /lib/x86_64-linux-gnu/amanda/amandad
  - /usr/lib64/amanda/amandad
  - /usr/libexec/amanda/amandad
  - /usr/lib/amanda/amandad
  - /usr/local/libexec/amanda/amandad
  - /usr/local/libexec/amandad

#These go in vars local to role, to avoid a problem with other imports
#ambind_fix_alias1: >
# alias amdump='echo "amdump, refusing invocation - This is a client, but we had to install the server package to fix amrecover (this message is a .bash_profile alias)"'
#ambind_fix_alias2: >
# alias amcheck='echo "amcheck, refusing invocation - This is a client, but we had to install the server package to fix amrecover (this message is a .bash_profile alias)"'
#ambind_bash_profile_dict: { 'alias amdump': "{{ ambind_fix_alias1 }}", 'alias amcheck': "{{ ambind_fix_alias2 }}" }

# list of known locations to search for ambind (depending on distro/package etc.)
ambind_search_paths:
  - /lib/x86_64-linux-gnu/amanda/ambind
  - /usr/lib64/amanda/ambind
  - /usr/lib/amanda/ambind

#-END-OS--VARS------------------------------------

#-----VAGRANT--VARS-------------------------------
#vagrant_net_regex: '192.168.[0-9]*.[0-9]*'
#-END-VAGRANT--VARS-------------------------------

#--------------------------------------------------------------------------------

...
